### PR TITLE
fix: completion block updates dispatch to callbackQueue

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).

### Issue Description

When using completion blocks to save/update/fetch etc. the result may not return to the specified callback queue.

### Approach

For completion block code that uses async/await, always dispatch back to queue. 

### TODOs before merging

- [x] Add tests
- [x] Add entry to changelog

### CODE REVIEW

**Comment by cbaker6** [comment]
@Aziz-AnyDesk here's a fix to the callback issue you mentioned. Note that I no longer support the parseplatform version of Parse-Swift (you can see why [here](https://github.com/netreconlab/Parse-Swift/discussions/7#discussion-4497222) if you are interested). I recommend you point to this repo as this is where I post all updates. The parseplatform one is already out-of-date.

**Comment by Aziz-AnyDesk** [comment]
Hi.

Thanks for your contributions to ParseSwift.

It would be great if you could also publish your repo to cocoapods. Our project uses cocoapods for dependency management but your repo seems to be available only on SPM and Carthage.

Thanks in advance
Best regards

On 22. Nov 2022, at 21:01, Corey ***@***.***> wrote:


This mail comes from outside of the company. Take care when opening links or attachments.



@Aziz-AnyDesk<https://github.com/Aziz-AnyDesk> here's a fix to the callback issue you mentioned. Note that I no longer support the parseplatform version of Parse-Swift (you can see more here<https://github.com/netreconlab/Parse-Swift/discussions/7#discussion-4497222>). I recommend you point to this repo as this is where I post all updates. The parseplatform one is already out-of-date.

**Comment by cbaker6** [comment]
@Aziz-AnyDesk #28 will add back cocoa pods but you will need to link to the [repo directly](https://github.com/netreconlab/Parse-Swift#cocoapods) as I don't plan to push a pod for this. The reasons are Cocoapods hasn't released a version since earlier this year and doesn't seem to build releases for the latest Xcode, SPM can be easily added to apps and is more flexible with less work.

**Comment by cbaker6** [comment]
@Aziz-AnyDesk version 5.3.1 is now on cocoa pods and future releases should automatically show up. Follow the directions here: https://github.com/netreconlab/Parse-Swift#cocoapods

**Comment by cbaker6** [comment]
@lsmilek1 the callback queue issue was resolved in this PR. I recommend you use this repo for ParseSwift as the parseplatform repo is no longer maintained. You can see details of feature comparisons and how to migrate here: https://github.com/netreconlab/Parse-Swift/discussions

**Pull request merged**
