### PR TITLE
feat: Add retrieve Parse Server version and information

### PR DESCRIPTION
**Pull request by cbaker6**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [ ] I am creating this PR in reference to an [issue](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).

### Issue Description

Currently there's no way to access the Parse Server version from ParseSwift along with additional information from the server.

### Approach

Convert the `ParseHealth` type to `ParseServer` and add methods: `health()` and `information()`:
- `health()` has the same behavior as `ParseHealth.check()`
- `information()` is new and requires ParseSwift to have access to the servers `primaryKey`. The method returns a new type called `Information` which will reveals the Server's version via a property called `version` which is of `ParseVersion` type. The `Information` type also has a method called, `getFeatures()` which can reveal the available features of the server

### TODOs before merging

- [x] Add tests
- [x] Add entry to changelog
- [x] Add changes to documentation (guides, repository pages, in-code descriptions)

### CODE REVIEW

**Comment by cbaker6** [comment]
@jaysonng This PR will add the ability to check the Parse Server version. If you haven't already checkout out [ParseServerSwift](https://github.com/netreconlab/parse-server-swift) be sure to do as it will let you write Cloud Code using ParseSwift

**Comment by jaysonng** [comment]
oh wow. awesome. I'm going to checkout ParseServerSwift right now.

**Comment by cbaker6** [comment]
@jaysonng great! This feature will be available in ParseServerSwift in a few hours after I add 1 more feature.

**Comment by cbaker6** [comment]
@jaysonng I added an example CloudCode function to access the version in ParseServerSwift, https://github.com/netreconlab/parse-server-swift/blob/9619d3c4d8a1dd22aa034385d10a758becfe1851/Sources/ParseServerSwift/routes.swift#L41-L89

**Comment by jaysonng** [comment]
regarding .hydrateuser() - I had a problem with it and was getting unauthorized access error. I figured out that it was because I have my users ACL set to only themselves who can access it. I fixed it by adding options: [.userPrimaryKey] to hydrateuser().

**Comment by cbaker6** [comment]
> regarding .hydrateuser() - I had a problem with it and was getting unauthorized access error. I figured out that it was because I have my users ACL set to only themselves who can access it. I fixed it by adding options: [.userPrimaryKey] to hydrateuser().

You shouldn't need to `.userPrimaryKey` unless you didn't properly conform to [ParseCloudUser](https://swiftpackageindex.com/netreconlab/parse-swift/5.7.3/documentation/parseswift/parseclouduser) on the server. `hydrateUser()` uses the `sessionToken` provided by the client app to fetch the user, so a user should always be able to fetch themselves. This ensures the user/ParseServerSwift only accesses data they are suppose to through your ACL and CLP settings.

Of course, if the user isn't logged in, they won't have a sessionToken. You can print out the user before you hydrate to see if your client is providing a sessionToken

**Comment by jaysonng** [comment]
> You shouldn't need to `.userPrimaryKey` unless you didn't properly conform to [ParseCloudUser](https://swiftpackageindex.com/netreconlab/parse-swift/5.7.3/documentation/parseswift/parseclouduser) on the server. `hydrateUser()` uses the `sessionToken` provided by the client app to fetch the user, so a user should always be able to fetch themselves. This ensures the user/ParseServerSwift only accesses data they are suppose to through your ACL and CLP settings.

I just use the default User.swift that you have with Parse-Server-Swift. unedited. 

I'll check on that some more later on.

**Pull request merged**
