### PR TITLE
Offline mode

### LINKED ISSUE #39: Add offline object saving
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I have searched through [existing issues](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).

### Current Limitation
It's not possible to use Parse-Swift offline.

### Feature / Enhancement Description
It would add offline object saving, related to the requested query.

### Example Use Case
```
var query = GameScore.query("points" > 50)
    .useLocalStore()
    .order([.descending("points")])
```

### Alternatives / Workarounds
None

### PR DESCRIPTION
**Pull request by vdkdamian**
### New Pull Request Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/netreconlab/Parse-Swift/security/policy).
- [x] I am creating this PR in reference to an [issue](https://github.com/netreconlab/Parse-Swift/issues?q=is%3Aissue).

### Issue Description
This adds the possibility to use ParseSwift with offline mode. Objects will be stored on device if needed and can be fetched when internet connection is back.

Closes: https://github.com/netreconlab/Parse-Swift/issues/39

### Approach
I will add playground examples on how to use it.

### TODOs before merging

- [ ] Test
- [x] Linting
- [x] Add tests
- [ ] Add entry to changelog
- [ ] Add changes to documentation (guides, repository pages, in-code descriptions)
- [x] Add playground examples

### CODE REVIEW

**Comment by vdkdamian** [comment]
First 4 commits are not correct, don't know how to get em out

**Comment by vdkdamian** [comment]
I think I need to change the moment om saving the objects locally. 
I would need to save to result from a `saveCommand` in order to get the correct `updatedAt` date.

@cbaker6 What do you think about this approach?

**Comment by cbaker6** [comment]
You will need to resolve the merge conflicts and design the local storage following what I mentioned here, https://github.com/parse-community/Parse-Swift/projects/2#card-53117524 to be considered for this repo.

You also didn't fork from this repo, so this PR won't work as is.

**Comment by vdkdamian** [comment]
> You will need to resolve the merge conflicts and design the local storage following what I mentioned here, https://github.com/parse-community/Parse-Swift/projects/2#card-53117524 to be considered for this repo.

Do you think there is something usefull in my code? I looked at the project you mentioned. Seems like a total different approach. Still would look forward if I can help. 
I'm learning a lot from you so any help would be appreciated 🙂 

> You also didn't fork from this repo, so this PR won't work as is.
I'll fix this as soon as possible!

**Comment by cbaker6** [comment]
From your posts, you have designed this for the parse-community Parse-Swift with the intent of getting it accepted there. I recommend you reach out to them and ask for a code review. I will not review code that’s intended for that repo.

**Pull request closed without merging**
